### ISSUE TITLE
Company Car not stored

### ISSUE THREAD

**Issue by midgetman111** [TheHorizonRP/Issues#4]
Describe the bug
Company UWU van has not been stored in the garage. It was stored yesterday during CEO testing and now it is not there. Says NoCarFound
To Reproduce
Store car, open garage, not there
Screenshots / Videos
![image](https://user-images.githubusercontent.com/73799019/208256440-033ed514-df5f-413c-8053-f16587c2a225.png)

Additional context

**Comment by midgetman111** [comment]
Issue is fixed, but now am unable to pull the vehicle 
Will attach a video
https://streamable.com/16oz2b

**Comment by takinatf** [comment]
This issue has been resolved
